# Get all BCO-DMO Instruments
# @title BCO-DMO Instruments
# @author Adam Shepherd
# @endpoint http://linked.bco-dmo.org/sparql
# @see http://www.bco-dmo.org
# @see http://linked.bco-dmo.org
# @see http://linked.bco-dmo.org/sparql
# @tag BCO-DMO
# @tag instruments
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bcodmo: <http://escience.rpi.edu/ontology/BCO-DMO/bcodmo/3/0/>

DESCRIBE ?instr
WHERE {
  ?instr rdf:type bcodmo:Instrument .
}
