# Get all BCO-DMO People
# @title BCO-DMO People
# @author Adam Shepherd
# @endpoint http://linked.bco-dmo.org/sparql
# @see http://www.bco-dmo.org
# @see http://linked.bco-dmo.org
# @see http://linked.bco-dmo.org/sparql
# @tag BCO-DMO
# @tag people
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
DESCRIBE ?person
WHERE {
  ?person rdf:type foaf:Person .
}
